### ISSUE TITLE
Workflow creation failed with the latest updates

### ISSUE THREAD

**Issue by karthikkc24** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#126]
1. In [Exercise-1 Task-2 Step-10](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-2-build-automation-with-github-registry), workflow creation getting failed with the latest updates. 

    Encountered the following error:

    ![image](https://user-images.githubusercontent.com/83394010/162982164-97f2720f-af6c-40dc-96b5-063a05f0cea6.png)

2. With the latest updates, a step which instructs to rename the workflow file name has been removed. Which is resulting in confusion while adding a workflow either it is for fabrikam-web, fabrikam-api or fabrikam-init.

3. In [Exercise-1 Task-1 Step-5](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-4-using-dependabot), while trying to **commit and push** the changes through Powershell, encountered an error that "**cannot push the changes before pulling the repo**". PFB screenshot FYR. Found that tasks (Current Task 4-Using Dependabot was part of Task-2 of Exercise-1 and Task-1 Set-up Local Infrastructure was part of Task-3 of Exercise-1 earlier) got changed which might caused this issue.

    ![image](https://user-images.githubusercontent.com/83394010/162985177-70c7da0f-a41c-4179-9b64-e2fc7f2cde25.png)

4. Found that instructions are not so clear to perform [Task-3 Editing the GitHub Workflow File Locally of Exercise-1](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-3-editing-the-github-workflow-file-locally).

**Comment by sadukie** [comment]
Addressing Karthik's points:

1. For the signing error - it looks like I left the note in [Exercise 1, Task 3, Step 3, Note 2](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-3-editing-the-github-workflow-file-locally) - I will move this note higher up so that it is with the code that runs into this problem.

2. I will investigate this. The file should now be named `docker-publish.yml`.  The new change will create one workflow file with all 3 Docker images addressed conditionally. 
* [Exercise 1, Task 2](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-2-build-automation-with-github-registry) will get you through creating a workflow using the GitHub editing tool.
* [Exercise 1, Task 3]()https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-3-editing-the-github-workflow-file-locally has you edit the workflow file so that it conditionally updates the images based on which files are changed.

3. I am confused. Are you running through the updates with an existing repo? I see you mention Exercise 1 Task 1 but then refer to Task 4.   If you're making changes in the browser, then you need to do a `git pull` locally before doing a `git push`.  Where are you running into the problem where you have to pull before pushing? I can update the instructions once I better understand where you are running into this problem.

4. @karthikkc24 What if I update Task 3 with the following steps:
* Pull the changes from GitHub
* Copy the file. (I can specify the folder path you should be in as well as the PowerShell command if that will help.)
* Commit to the repo, then push to GitHub. (I can call out those commands explicitly if that will help.)
* Navigate to the Packages tab in your GitHub account.

Would it help if I pulled the details of what the files does above the steps for that task?

**Comment by kalyani7744** [comment]
Hello @sadukie, 

1. We are performing the lab using updated Microsoft Repo. In [Exercise 1, Task 1, Step 5](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-1-set-up-local-infrastructure), the commands to commit and push are missing from the lab guide. While pushing the changes in PowerShell from local repository to GitHub, we are facing the below error.

![image](https://user-images.githubusercontent.com/83349665/163203633-50d6a3f7-2e05-4ed4-8d86-eb6b0cbdcb37.png)

- We were able to resolve the above error by running the **git pull** command before commit and push. Can you please update the lab guide accordingly.

2. In [Exercise 1, Task 3](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-3-editing-the-github-workflow-file-locally), we have followed the steps mentioned by you but we are running into an issue. The workflow run for api, web and init docker images is getting skipped and the packages are not getting created inside repository.

![image](https://user-images.githubusercontent.com/83349665/163199448-aa207dd4-8ad1-42dd-bf18-297940b1d560.png)

 - Can you please look into the issue as we are not able to proceed further as the packages are not created.

**Comment by sadukie** [comment]
@karthikkc24 With regards to those images being skipped:

* Make a change in the `content-api` folder. I test with changing a comment in the Dockerfile.
* Commit that change to the repo.
* Push the commit to GitHub.

This should trigger the "Update the API Docker image" job.

Next:

* Make a change in the `content-init` folder. I test with changing a comment in the Dockerfile.
* Commit that change to the repo.
* Make a change in the `content-web` folder. I test with changing a comment in the Dockerfile.
* Commit that change to the repo.
* Push these commits to GitHub.

This should trigger the "Update the Init Docker image" and "Update the Web Docker image" jobs.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PE #127
