### ISSUE TITLE
Best-practice for Solution architecture

### ISSUE THREAD

**Issue by estensen** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#37]
How is merging with the master branch before running build and test best practice? If either build or test fails your errors and bugs will propagate to other developers, because they will pull the latest code from the master branch when they develop.

**Comment by estensen** [comment]
Attended an event, "Discover workshop: Continuous delivery in Azure DevOps" in Oslo, where we were told that [it](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#solution-architecture) was "the solution preferred by Microsoft".

Maybe make the cons of this solution clearer in the docs?

**Comment by waltermyersiii** [comment]
estensen: We need to update the workshop to make the check ins a PR so it won't break the build. Adding @sdabbiru  and @dmckinstry for visibility.

**Comment by waltermyersiii** [comment]
Oops, @sdavis3, not @sdabbiru.

**Comment by waltermyersiii** [comment]
Hi all. Nix that. I see that we actually do implement the PR for review. So please disregard.

**Comment by dmckinstry** [comment]
Ok - I've dug in and basically agree with the original intent. If we really want to show best practices, we should (1) have a PR build that compiles and tests but doesn't package, (2) a branch policy that requires the PR build and (3) a separate CI build that triggers on Master (post-pr merge), uses the PR build as a template but adds the publishing steps.

So the question is, how far do we want to go?

**Comment by waltermyersiii** [comment]
We will meet and plan for the next update. @sdavis3 @DawnmarieDesJardins

**Comment by DawnmarieDesJardins** [comment]
Thanks all.  Marking this issue as an enhancement so the comments above will be taken into consideration at the next scheduled update.

**Comment by OsirisTerje** [comment]
The "Microsoft solution" was part of the trainer presentation, and the page 19 there show a Preferred Solution from Microsoft that states what @estensen says above.  
<img width="844" alt="Annotation 2019-09-25 125225" src="https://user-images.githubusercontent.com/203432/65595314-c97bd300-df94-11e9-8f9e-70e0d50ab971.png">

I've changed this in https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/pull/39 so that it matches the way we teach it to be:

<img width="1093" alt="Annotation 2019-09-25 125224" src="https://user-images.githubusercontent.com/203432/65595371-f4febd80-df94-11e9-8f77-9d1b7f1c5a12.png">

The build yaml file for the CI build described here: https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md,  also need to be changed to reflect that it should trigger on all branches, and Exercise 6 should be extended to include creating a PR policy that will trigger a PR build, using the same build definition.

**Comment by OsirisTerje** [comment]
@dmckinstry  The CI build doesn't really do any real publishing.  It only creates the artifact and stores that away.  So I don't think there is any need for different builds.  If one want to skip one of the steps, a simple condition could do that.   I tried it out now (without condition), and it worked quite nice as is.  What is needed though is to block the release pipeline from triggering on anything but builds from the master branch.   Unless one want to e.g. have test env populated from PR branches.

**Comment by OsirisTerje** [comment]
I have also added the  information in the HOL Step by step on how to set up a branch policy using the builds. See https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/pull/40

**Comment by OsirisTerje** [comment]
Ping :-)

**Comment by waltermyersiii** [comment]
@sdavis3. Please look at Osiris' suggestions.

**Comment by waltermyersiii** [comment]
@OsirisTerje, please do not issue PRs. Only our vendor partners can issue PRs for prescribed updates. Please submit as an issue instead, or point us to your fork with your updates.

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Adding Paul as he was looking into the open PRs.

**Comment by sdavis3** [comment]
I concur this would be a good change. Let's tackle it in the next update.

**Comment by OsirisTerje** [comment]
@waltermyersiii  The fork (and branch)is at https://github.com/solidify/MCW-Continuous-delivery-in-Azure-DevOps/tree/workshopSept25  

FWIW:  I also find it a bit counter-productive to not accept pull requests to an open-source project.  I would suggest you reevaluate that policy. It could also speed up your release schedule. 

We're running the workshops (at Microsoft) in Oslo, and have two more this autumn, and will use the fork for those.  It would have been good to use the "official" site for the workshops, less explaining.

**Comment by paulopsgility** [comment]
This is resolved in the March 2020 test fix
