### ISSUE TITLE
Exercise 1 Task 4,5,6

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#49]
The path and the screenshots mentioned in the lab guide for the command   
az group deployment create --resource-group $resourceGroupName --template-file "$HOME/azuredeploy.json"  (Exercise1:Step 1 of  task4,task5 ,task6) does not match with the actual path i.e   az group deployment create --resource-group $resourceGroupName --template-file "$HOME/studentfiles/armtemplate/azuredeploy.json" .
Can you please verify and update as soon as possible.

**Comment by akn9050** [comment]
Also in [exercise 4 task 1.9](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-1-create-a-release-definition) can we update the authorization with advance option, so instead of authorizing on subscription level, we can select the advance option and select tailspin toys RG, so it will be easy if we don't want to give subscription level authentication.

![authorise01](https://user-images.githubusercontent.com/27498287/68307932-08439380-00d2-11ea-8917-4adf7a223251.png)

![authorise02](https://user-images.githubusercontent.com/27498287/68307946-0d084780-00d2-11ea-894b-9a6a525b5dd0.png)

**Comment by paulopsgility** [comment]
We are doing a test/fix this month (Nov). We'll review and update as necessary.
