### ISSUE TITLE
Using a pre-defined Resource Group

### ISSUE THREAD

**Issue by tylerd** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#59]
The cloudlabs.ai lab provider, along with many organizations, do not provide users full access to a Subscription to perform the tasks related to this HOL. The user will have a pre-defined Resource Group which they are given Contributor or Owner access to.

Lack of Subscription-level access causes issues with the HOL steps, specifically:

* Users cannot initialize the Cloud Shell using the default settings, they have to go into the Advanced settings and create a custom Storage Account
* Users have to enter the existing Resource Group name in Task 4 Step 2 (and Task 5, 6 step 2). Entering a Resource Group name that does not exist causes an error because it cannot be created
* If users are entering an existing RG in Task 4 Step 2, they have to enter the correct location of that Resource Group. If they enter a different location than the existing RG they will get an error, because the location cannot be changed (this is the same for Task 5 and 6 step 2)

**Comment by DawnmarieDesJardins** [comment]
@tylerd - Thanks Tyler.  I reached out to the cloudlabs group for additional information of you issue.  This is their response.  I'm adding in our authors to look at the first bullet and review for the upcoming test/fix.

•	Users cannot initialize the Cloud Shell using the default settings, they have to go into the Advanced settings and create a custom Storage Account.
o	Users can create the Cloud Shell by using below mentioned approach. We can add this approach in the lab guide also.
	Click on the Bash tab, Then,  in the Storage mounting page, Select "Show Advanced Settings". In the next page, provide the following details.    
	Resource group : Click on use existing and select resource group named as ODL-xxx-xxxx. 
	Storage account name : Provide any unique name. 
	File share : Provide any unique name.
	Click on Create Storage

•	Users have to enter the existing Resource Group name in Task 4 Step 2 (and Task 5, 6 step 2). Entering a Resource Group name that does not exist causes an error because it cannot be created.
o	We are providing the pre-created Resource group and it is mentioned in the lab guide also that user have to use resource group with name “TailspinToysRG”. So, user’s should enter the RG name which is pre-created with name “TailspinToysRG”.

•	If users are entering an existing RG in Task 4 Step 2, they have to enter the correct location of that Resource Group. If they enter a different location than the existing RG they will get an error, because the location cannot be changed (this is the same for Task 5 and 6 step 2)
o	Yes, users have to select the correct location of the Resource group. We are providing these instructions in lab guide in each user’s lab environment details.

**Comment by paulopsgility** [comment]
@DawnmarieDesJardins bullet one is a custom instruction that only applies to the cloudlabs environment. Normal subscriptions (paygo, trial, msdn, visualstudio, CSP, Opsgility lab environment etc) do not need these extra steps, it just works.

**Comment by tylerd** [comment]
Thank you for reaching out to the cloudlabs team @DawnmarieDesJardins 

In my experience running the cloudlabs lab, the situation was more complex than the above response, for example the participant needs to enter the "TailsponToys-RG-11596" resource group name, where the number is basically random, based on their lab. If that specific name was in the guide it would be better, but it is not. Also with the location, there was nothing in the guide that stated that you need to enter the existing location of the resource group.

That said, there are many portions of the lab guide that could be tailored to the cloudlabs environment, the shell init, creating the initial resources, the Azure AD Service Principal steps, connecting Azure DevOps and the Azure Subscription / Resource Group.
If i was running this lab again, I would rather tailor the steps specifically for the cloudlabs environment, because that is the lab that we provide in our Microsoft marketing events.

So .. should there be a fork of this guide, so that we can collaborate on the specific cloudlabs.ai requirements?

**Comment by DawnmarieDesJardins** [comment]
@tylerd
Thanks for the specifics Tyler.  As far as forking the repo, cloudlabs is separate from the MCW team so forking the repo won't help us in this case.  I have sent your feedback to my contact and they replied they will have their team review their documentation and make changes accordingly.  Closing this issue.
