### ISSUE TITLE
Pipeline failure in Exercise3

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#73]
In [Exercise3 Task1](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-1-create-a-build-pipeline) step4, the pipeline execution failed.
Please find the screenshots and log file of the pipeline below for reference.

![issue1](https://user-images.githubusercontent.com/52440474/100439633-c82ec480-30c9-11eb-949f-57b6f5b01351.png)

[1_Job (1).txt](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/files/5607319/1_Job.1.txt)

We have workshop scheduled next week. Please try to fix this asap.

**Comment by eaelmoneem1** [comment]
Hi tejaswini972
I faced the same issue and I was able to resolve it, I'm adding here the steps for everyone:
-netcoreapp2.2 is not supported anymore so you need to use at least 3.1
-Using netcoreapp3.1 will require to use a new SKD version, You can see the full list here:
https://dotnet.microsoft.com/download/dotnet-core/3.1

So what you need to do is:
1-Create global.json  "This will contains the SDK version"file with :
{
  "sdk": {
    "version": "3.1.102",
    "rollForward": "latestFeature"
  }
}

2-In tailspintoysweb.csproj:
      modify the first line to read the SDK version from global.jsonfile: <Project Sdk="Microsoft.NET.Sdk"> 
	  2-Change netcoreapp from 2.2 to 3.1
	  3-add the following refrences ,They are needed for the new SDK:
	<PackageReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
        <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="3.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="3.1.0" />

3-Update the NuGet version in the azure-pipelines.yaml to 5.8.0

push all the changes to the master and check your pipeline.

**Comment by tejaswini972** [comment]
Hi @eaelmoneem1 

Will try this and thanks for the update!

**Comment by himanshuahlawat31** [comment]
Hi we have tried workaround pipeline is getting failed
![image](https://user-images.githubusercontent.com/57964598/100659324-79f21d80-3376-11eb-81c9-b730e3723aed.png)

@DawnmarieDesJardins @mwasham @dwnatwick can you please suggest something for this.

we have lab scheduled for tomorrow

**Comment by blgorman** [comment]
@eaelmoneem1 
Could you clarify your comments?
Specifically, 
- what is the command  to put in the first line of the csproj?
- Where are you changing from 2.2 to 3.1
- What references specifically?  They are blank in the above thread.

Thanks

@tejaswini972 
The updates to the latest versions of .Net have caused .Net Core 2.2 to no longer work.
I'm currently spinning up a .Net 5 version of the app.  I will try to test with the current build and then see what needs to be modified and get you that information ASAP, if I can get it to work.

**Comment by blgorman** [comment]
@himanshuahlawat31 
I added the global.json file as per @eaelmoneem1 above and did nothing else, and my build succeeded.  

![step01](https://user-images.githubusercontent.com/785214/100674161-586b4480-332a-11eb-86b4-d19d145ff91c.png)
![step02](https://user-images.githubusercontent.com/785214/100674162-586b4480-332a-11eb-878a-8eb2c4774540.png)
![step03](https://user-images.githubusercontent.com/785214/100674163-586b4480-332a-11eb-9424-22cd5dee0c95.png)
![step04](https://user-images.githubusercontent.com/785214/100674154-573a1780-332a-11eb-9fa5-4ebecfcdf1d9.png)
![step05](https://user-images.githubusercontent.com/785214/100674156-57d2ae00-332a-11eb-960f-bb48385f7484.png)
![step06](https://user-images.githubusercontent.com/785214/100674157-57d2ae00-332a-11eb-9535-6b2d8d10375d.png)
![step07](https://user-images.githubusercontent.com/785214/100674159-57d2ae00-332a-11eb-8d69-02eb6942000c.png)

**Comment by himanshuahlawat31** [comment]
Hi @blgorman i created global.json file in the project and updated the project file with dotnet version 

![image](https://user-images.githubusercontent.com/57964598/100674694-92b8fe00-338b-11eb-9fa3-04ec566f017c.png)
![image](https://user-images.githubusercontent.com/57964598/100674733-a4020a80-338b-11eb-859f-9cf7e89f7fb7.png)
but pipeline is still failing

**Comment by blgorman** [comment]
what happens if you put the target framework back to 2.2
`<TargetFramework>netcoreapp2.2</TargetFramework>`

**Comment by himanshuahlawat31** [comment]
Yes that worked, thanks

**Comment by opsgilitybrian** [comment]
In the meantime, I am working on a .Net 5 solution and I have it working locally, but it will take some time to get the updates into the documentation.   

This solution is not endorsed, but may work as a work-around if you want to test/try this option for using .Net 5 instead of .Net core 2.2.  Note that there is no actual use of the database in this application, however I do not think the original one was using the database either.

If you want to do a .Net 5 version, you would need to follow the original HOL setup, but instead of the zip file you would need to get this one and put these files in your repo: 
[.Net 5 Tailspin Toys Web](https://github.com/opsgilitybrian/TailspinToysWeb5/raw/master/TailsPinToys5.zip)

Additionally, after you run the ARM templates, you have to update the app service to use preview 5.  There are 6 of them (2 dev, 2 test, and 2 prod)

![updateappservice](https://user-images.githubusercontent.com/66644214/100678577-201c3400-3333-11eb-8c03-f3600cdb43bb.png)

You would then need to completely change the first build definition to match the following: 
`stages:
- stage: Build
  displayName: 'Build Stage'
  jobs: 
  - job: Build
    pool:
      vmImage: 'windows-latest'
      demands:
      - msbuild
      - visualstudio
      - vstest

    variables:
      buildConfiguration: 'Release'

    steps:
    # Nuget Tool Installer Task
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 5.5.1'
      inputs:
        versionSpec: 5.5.1      

    # Nuget Restore Task
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '**/tailspintoysweb.csproj'

    # Node.js Tool Installer Task
    # Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x' 

    # Build Task  
    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    # Publish Task
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
      condition: succeededOrFailed()
      `

Also
* Do not modify package.json
* As per original instructions, you do want to delete the package-lock.json file
* Although there may be updates, the deploy steps should work as originally written as long as you have the connection setup correctly as well as the correctly named app services and resource groups.
* Note that all of the tools in the build are updated, including the NugetInstaller, NugetRestore, the Node Version, and .Net CLI builder

**Comment by eaelmoneem1** [comment]
> @eaelmoneem1
> Could you clarify your comments?
> Specifically,
> 
> * what is the command  to put in the first line of the csproj?
> * Where are you changing from 2.2 to 3.1
> * What references specifically?  They are blank in the above thread.
> 
> Thanks
> 
> @tejaswini972
> The updates to the latest versions of .Net have caused .Net Core 2.2 to no longer work.
> I'm currently spinning up a .Net 5 version of the app. I will try to test with the current build and then see what needs to be modified and get you that information ASAP, if I can get it to work.

Sorry, I have missed adding the references :
I saw that you have another workaround, but I'm adding mine for any case.

![image](https://user-images.githubusercontent.com/50662268/100709192-551d9a80-33b6-11eb-8eb3-3813183d387c.png)
