### ISSUE TITLE
Issue in Exercise4 Task1

### ISSUE THREAD

**Issue by tejaswini972** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#75]
[Exercise4 Task1 Step13](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-1-modify-yaml-definition-to-create-a-multistage-pipeline)
 Pipeline got failed. 
However it worked when I updated the parameter **PackageForLinux** from `$(System.ArtifactDirectory)/**/*.zip` to `$(Build.ArtifactStagingDirectory)/drop/*.zip`.

[Exercise4 Task1 Step14](https://github.com/microsoft/MCW-Continuous-delivery-in-Azure-DevOps/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Continuous%20delivery%20in%20Azure%20DevOps.md#task-1-modify-yaml-definition-to-create-a-multistage-pipeline)
Not able to view the **Tailspintoys** application page.

 I added a task  which will swap the slots from **staging** to **production** in the yaml file, then I was able to view the tailspintoys application page.

**Comment by franklinbrian** [comment]
Ex4 Task1 Step 13 -
Yes, that is a fix that is needed in the YAML. 

Ex4 Task1 Step 14 -
You should not add a task to switch the slots.  The point of this is to get things into the staging slot where you can then review them.  All the slots are accessible on the web just like the production slot.  When you drill into your app service for production, you need to then look at the slots, then click on the staging slot.  The staging slot has its own url

https://yoursitename-staging.azurewebsites.net
instead of
https://yoursitename.azurewebsites.net

By deploying directly to production, you circumvent any testing and qa and that could be a real problem in the real world.

Once QA is done on the staging slot, you should just use Azure and push the button to swap slots.

**Comment by opsgilitybrian** [comment]
@tejaswini972 
Ex4 Task1 Step 13 -
Yes, that is a fix that is needed in the YAML.  Thank you for pointing this out.  The images have the fix but I've added an instruction at step 6 to make sure it's not missed in the future. 

Ex4 Task1 Step 14 -
You should not add a task to switch the slots. The point of this is to get things into the staging slot where you can then review them. All the slots are accessible on the web just like the production slot. When you drill into your app service for production, you need to then look at the slots, then click on the staging slot. The staging slot has its own url

https://yoursitename-staging.azurewebsites.net
instead of
https://yoursitename.azurewebsites.net

By deploying directly to production, you circumvent any testing and qa and that could be a real problem in the real world.

Once QA is done on the staging slot, you should just use Azure and push the button to swap slots.

@DawnmarieDesJardins @mwasham @dwnatwick 
I have added text at step 6 in task 4 to call out the need to fix the packageForLinux line as brought up in this issue.
